<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rating__scr_post_optionsstats-listste_79477d</name>
   <tag></tag>
   <elementGuidId>99165c4a-fc43-4f37-8b49-d5048ef842d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='_scr_post_options[stats-list][stephen][rating]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;_scr_post_options[stats-list][stephen][rating]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scr_post_options[stats-list][stephen][rating]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>csf-input-number csf--is-unit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depend-id</name>
      <type>Main</type>
      <value>rating</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scr_post_options&quot;)/div[@class=&quot;inside&quot;]/div[@class=&quot;csf csf-metabox csf-theme-light&quot;]/div[@class=&quot;csf-wrapper&quot;]/div[@class=&quot;csf-content&quot;]/div[@class=&quot;csf-sections&quot;]/div[@class=&quot;csf-section&quot;]/div[@class=&quot;csf-field csf-field-fieldset&quot;]/div[@class=&quot;csf-fieldset-content&quot;]/div[@class=&quot;csf-field csf-field-fieldset&quot;]/div[@class=&quot;csf-fieldset-content&quot;]/div[@class=&quot;csf-field csf-field-slider&quot;]/div[@class=&quot;csf-fieldset&quot;]/div[@class=&quot;csf--wrap&quot;]/div[@class=&quot;csf--input&quot;]/input[@class=&quot;csf-input-number csf--is-unit&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='_scr_post_options[stats-list][stephen][rating]']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scr_post_options']/div[2]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
