<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_criteria 1_star outline icon - Copy (1)</name>
   <tag></tag>
   <elementGuidId>98d17bd2-c8ee-4010-b808-0a7794498a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;post-13&quot;]/div/div/form/div[5]/ul/li[1]/div[2]/div[1]/i[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;post-13&quot;)/div[@class=&quot;ast-post-format- ast-no-thumb single-layout-1&quot;]/div[@class=&quot;entry-content clear&quot;]/form[@class=&quot;ui form scr-user-review active&quot;]/div[@class=&quot;rating fields&quot;]/ul[@class=&quot;review-list&quot;]/li[@class=&quot;review-item inline field&quot;]/div[@class=&quot;review-item-stars&quot;]/div[@class=&quot;stars-wrapper&quot;]/i[@class=&quot;star outline icon&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star outline icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-13&quot;)/div[@class=&quot;ast-post-format- ast-no-thumb single-layout-1&quot;]/div[@class=&quot;entry-content clear&quot;]/form[@class=&quot;ui form scr-user-review active&quot;]/div[@class=&quot;rating fields&quot;]/ul[@class=&quot;review-list&quot;]/li[@class=&quot;review-item inline field&quot;]/div[@class=&quot;review-item-stars&quot;]/div[@class=&quot;stars-wrapper&quot;]/i[@class=&quot;star outline icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-13']/div/div/form/div[2]/ul/li/div[2]/div/i[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/ul/li/div[2]/div/i[5]</value>
   </webElementXpaths>
</WebElementEntity>
