<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter the Post ID (or) Page ID_starca_4f486d</name>
   <tag></tag>
   <elementGuidId>55b9c583-1fcd-43e5-bd86-573ec86c33c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='starcat_review_user_review_form[post_id]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;starcat_review_user_review_form[post_id]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>starcat_review_user_review_form[post_id]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depend-id</name>
      <type>Main</type>
      <value>post_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;csf-modal-starcat-review-shortcode&quot;)/div[@class=&quot;csf-modal-table&quot;]/div[@class=&quot;csf-modal-table-cell&quot;]/div[@class=&quot;csf-modal-inner&quot;]/div[@class=&quot;csf-modal-content&quot;]/div[@class=&quot;csf-modal-load&quot;]/div[@class=&quot;csf-fields&quot;]/div[@class=&quot;csf-field csf-field-text&quot;]/div[@class=&quot;csf-fieldset&quot;]/input[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='starcat_review_user_review_form[post_id]']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='csf-modal-starcat-review-shortcode']/div/div/div[2]/div[3]/div[2]/div/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div/div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
